from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch
import os
from datetime import date

REPORTS_DIR = "reports"
os.makedirs(REPORTS_DIR, exist_ok=True)

BRAND = colors.HexColor("#10B981")
DARK = colors.HexColor("#18181B")
LIGHT = colors.HexColor("#F4F4F5")
MUTED = colors.HexColor("#71717A")


def _footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(MUTED)
    canvas.drawCentredString(A4[0] / 2, 0.5 * inch, "Generated by Autonomous BI Platform")
    canvas.restoreState()


def generate_pdf_report(dataset_name: str, summary: str, kpis: list, recommendations: list,
                        anomalies: list = []) -> str:
    filename = os.path.join(REPORTS_DIR, f"report_{dataset_name}.pdf")
    doc = SimpleDocTemplate(filename, pagesize=A4)
    styles = getSampleStyleSheet()
    body = ParagraphStyle("Body", parent=styles["Normal"], textColor=DARK, fontSize=10, leading=14)
    h2 = ParagraphStyle("H2", parent=styles["Heading2"], textColor=BRAND, fontSize=14, spaceAfter=8)

    elements = []

    # Title page
    elements.append(Spacer(1, 2.5 * inch))
    elements.append(Paragraph("Business Intelligence Report",
                              ParagraphStyle("Title", parent=styles["Title"], textColor=DARK, fontSize=24)))
    elements.append(Spacer(1, 10))
    elements.append(Paragraph(f"Dataset: {dataset_name}", styles["Normal"]))
    elements.append(Paragraph(f"Generated on: {date.today().isoformat()}", styles["Normal"]))
    elements.append(PageBreak())

    # 1. Executive Summary
    elements.append(Paragraph("1. Executive Summary", h2))
    elements.append(Paragraph(summary, body))
    elements.append(Spacer(1, 14))

    # 2. Key Performance Indicators
    elements.append(Paragraph("2. Key Performance Indicators", h2))
    if kpis:
        table_data = [["Measure", "Total", "Average", "Min", "Max"]]
        for k in kpis:
            table_data.append([k["measure"], k["total"], k["average"], k["minimum"], k["maximum"]])
        table = Table(table_data, hAlign="LEFT")
        style = []
        for i in range(len(table_data)):
            if i == 0:
                style.append(("BACKGROUND", (0, i), (-1, i), BRAND))
                style.append(("TEXTCOLOR", (0, i), (-1, i), colors.white))
                style.append(("FONTNAME", (0, i), (-1, i), "Helvetica-Bold"))
            else:
                style.append(("BACKGROUND", (0, i), (-1, i), colors.white if i % 2 == 0 else LIGHT))
        style += [
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("ALIGN", (1, 1), (-1, -1), "RIGHT"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ]
        table.setStyle(TableStyle(style))
        elements.append(table)
    else:
        elements.append(Paragraph("No key measures available.", body))
    elements.append(Spacer(1, 14))

    # 3. Anomalies Detected
    elements.append(Paragraph("3. Anomalies Detected", h2))
    if anomalies:
        for a in anomalies:
            z = a.get("z_score", "?")
            value = a.get("value", "?")
            elements.append(Paragraph(f"• Anomalous value {value} — z-score {z}", body))
    else:
        elements.append(Paragraph("No anomalies detected.", body))
    elements.append(Spacer(1, 14))

    # 4. Recommendations
    elements.append(Paragraph("4. Recommendations", h2))
    for i, rec in enumerate(recommendations or [], start=1):
        elements.append(Paragraph(f"{i}. {rec}", body))

    doc.build(elements, onFirstPage=_footer, onLaterPages=_footer)
    return filename